<?php
$food = array();

 $food[28] = array()

                $food[28]['category'] = 'Pasta Plus';
                $food[28]['name'] = 'Marinara Sauce';
                $food[28]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[28]['price'] = '8.50';
 $food[29] = array()
                $food[29]['category'] = 'Pasta Plus';
                $food[29]['name'] = 'Meat Sauce';
                $food[29]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[29]['price'] = '9.50';
  $food[30] = array()
                $food[30]['category'] = 'Pasta Plus';
                $food[30]['name'] = 'Meatballs or Sausage';
                $food[30]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[30]['price'] = '9.50';
  $food[31] = array()

                $food[31]['category'] = 'Pasta Plus';
                $food[31]['name'] = 'Mushrooms or Black Olives';
                $food[31]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[31]['price'] = '9.50';
  $food[32] = array()
                $food[32]['category'] = 'Baked Pasta';
                $food[32]['name'] = 'Lasagna';
                $food[32]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[32]['price'] = '9.50';
  $food[33] = array()
                $food[33]['category'] = 'Baked Pasta';
                $food[33]['name'] = 'Cannelloni';
                $food[33]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[33]['price'] = '9.50';
$food[34] = array()
               $food[34]['category'] = 'Baked Pasta';
               $food[34]['name'] = 'Manicotti';
               $food[34]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[34]['price'] = '9.50';
$food[35] = array()
               $food[35]['category'] = 'Baked Pasta';
               $food[35]['name'] = 'Stuffed Shells';
               $food[35]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[35]['price'] = '9.50';
 $food[36] = array()
               $food[36]['category'] = 'Baked Pasta';
               $food[36]['name'] = 'Cheese Ravioli';
               $food[36]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[36]['price'] = '9.50';
$food[37] = array()

               $food[37]['category'] = 'Baked Pasta';
               $food[37]['name'] = 'Baked Ziti';
               $food[37]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[37]['price'] = '9.50';
$food[38] = array()
               $food[38]['category'] = 'Baked Pasta';
               $food[38]['name'] = 'Baked Torellini';
               $food[38]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[38]['price'] = '9.50';
 $food[39] = array()
               $food[39]['category'] = 'Baked Pasta';
               $food[39]['name'] = 'Eggplant Parmigiana';
               $food[39]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[39]['price'] = '9.50';
$food[40] = array()

               $food[40]['category'] = 'Baked Pasta';
               $food[40]['name'] = 'Eggplant Rollatini';
               $food[40]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[40]['price'] = '9.50';
$food[41] = array()
               $food[41]['category'] = 'Baked Pasta';
               $food[41]['name'] = 'Pasta Combo';
               $food[41]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[41]['price'] = '9.50';
 $food[42] = array()
               $food[42]['category'] = 'Pasta Favorites';
               $food[42]['name'] = 'Fettuccine Molto Mio';
               $food[42]['description'] = 'Sun-dried tomatoes, onions, artichoke hearts & mushrooms in a creamy pink sauce';
               $food[42]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[42]['price'] = '10.50';
$food[43] = array()

               $food[43]['category'] = 'Pasta Favorites';
               $food[43]['name'] = 'Fettuccine Alfredo';
               $food[43]['description'] = 'Sauteed in a creamy cheese sauce';
               $food[43]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[43]['price'] = '10.50';
$food[44] = array()
               $food[44]['category'] = 'Pasta Favorites';
               $food[44]['name'] = 'Fettuccine Leonardo';
               $food[44]['description'] = 'Bacon and red onions in a creamy sauce';
               $food[44]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[44]['price'] = '10.50';
 $food[45] = array()
               $food[45]['category'] = 'Pasta Favorites';
               $food[45]['name'] = 'Ziti Vodka';
               $food[45]['description'] = 'Sauteed with prosciutto & red onions in a vodka-pink sauce';
               $food[45]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[45]['price'] = '10.50';
$food[46] = array()

               $food[46]['category'] = 'Pasta Favorites';
               $food[46]['name'] = 'Tortellini Michelangelo';
               $food[46]['description'] = 'Stuffed macaroni sauteed with onion, bacon, diced tomatoes & artichoke hearts in a pink sauce';
               $food[46]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[46]['price'] = '10.50';
$food[47] = array()
               $food[47]['category'] = 'Pasta Favorites';
               $food[47]['name'] = 'Tortellini Panne';
               $food[47]['description'] = 'Sauteed in a cream cheese sauce';
               $food[47]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[47]['price'] = '10.50';
 $food[48] = array()
               $food[48]['category'] = 'Pasta Favorites';
               $food[48]['name'] = 'Beef Ravioli';
               $food[48]['description'] = '(with your choice of sauce)';
               $food[48]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[48]['price'] = '10.50';
$food[49] = array()

               $food[49]['category'] = 'Pasta Favorites';
               $food[49]['name'] = 'Spinach Ravioli';
               $food[49]['description'] = '(with your choice of sauce)';
               $food[49]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[49]['price'] = '10.50';

 $food[70] = array()
               $food[70]['category'] = 'Neapolitan Style Pizza';
               $food[70]['name'] = 'Medium 14 inch pizza w/ cheese';
               $food[70]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[70]['price'] = '9.99';
$food[71] = array()
               $food[71]['category'] = 'Neapolitan Style Pizza';
               $food[71]['name'] = 'Large 16 inch pizza w/ cheese';
               $food[71]['imgURL'] = 'garlicBread.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[71]['price'] = '10.99';
$food[72] = array()
               $food[72]['category'] = 'Pizza Toppings';
               $food[72]['name'] = 'Pizza Toppings';
               $food[72]['description'] = 'Green Peppers, Beef Sausage, Canadian Bacon, Pepperoni, Cheese, Black Olives, Onions, Mushrooms, Anchovies, Jalapenos';
               $food[72]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[72]['price'] = '1.50';
 $food[73] = array()
               $food[73]['category'] = 'Specialty Toppings';
               $food[73]['name'] = '$1 Toppings';
               $food[73]['description'] = 'Fresh Garlic or Fresh Basil';
               $food[73]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[73]['price'] = '1.00';
$food[74] = array()

               $food[74]['category'] = 'Specialty Toppings';
               $food[74]['name'] = '$2 Toppings';
               $food[74]['description'] = 'Fresh Tomoatoes, Spinach, Extra Pizza Sauce';
               $food[74]['imgURL'] = 'garlicBread.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[74]['price'] = '2.00';
$food[75] = array()
               $food[75]['category'] = 'Specialty Toppings';
               $food[75]['name'] = '$3 Toppings';
               $food[75]['description'] = 'Riccota Cheese';
               $food[75]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[75]['price'] = '3.00';
 $food[76] = array()
               $food[76]['category'] = 'Specialty Toppings';
               $food[76]['name'] = '$4 Toppings';
               $food[76]['description'] = 'Grilled Chicken, Artichoke Hearts, Alfredo Sauce, Italian Sausage, Meatballs';
               $food[76]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[76]['price'] = '4.00';
$food[77] = array()

               $food[77]['category'] = 'Specialty Pizza';
               $food[77]['name'] = 'Special Medium Pizza';
               $food[77]['imgURL'] = 'garlicBread.jpg';
               $food[77]['price'] = '13.99';
$food[78] = array()
               $food[78]['category'] = 'Specialty Pizza';
               $food[78]['name'] = 'Special Large Pizza';
               $food[78]['imgURL'] = 'FriedCheese.jpg';
               $food[78]['price'] = '15.99';
 $food[79] = array()
               $food[79]['category'] = 'Specialty Pizza';
               $food[79]['name'] = 'Sicilian Deep Dish - Cheese';
               $food[79]['imgURL'] = 'FriedCheese.jpg';
               $food[79]['price'] = '14.99';
$food[80] = array()

               $food[80]['category'] = 'Specialty Pizza';
               $food[80]['name'] = 'Special Deep Dish';
               $food[80]['imgURL'] = 'garlicBread.jpg';
               $food[80]['price'] = '19.99';
$food[81] = array()
               $food[81]['category'] = 'Specialty Pizza';
               $food[81]['name'] = 'Stromboli with All Pizza Ingredients';
               $food[81]['imgURL'] = 'FriedCheese.jpg';
               $food[81]['price'] = '8.50';
 $food[82] = array()
               $food[82]['category'] = 'Specialty Pizza';
               $food[82]['name'] = 'Calzone w/ Sausage, Ricotta, & Mozzarella';
               $food[82]['imgURL'] = 'FriedCheese.jpg';
               $food[82]['price'] = '8.50';
$food[83] = array()

               $food[83]['category'] = 'Desserts';
               $food[83]['name'] = 'Plain Cheesecake';
               $food[83]['imgURL'] = 'garlicBread.jpg';
               $food[83]['price'] = '5.99';
$food[84] = array()
               $food[84]['category'] = 'Desserts';
               $food[84]['name'] = 'Chocolate Cheesecake';
               $food[84]['imgURL'] = 'FriedCheese.jpg';
               $food[84]['price'] = '5.99';
 $food[85] = array()
               $food[85]['category'] = 'Desserts';
               $food[85]['name'] = 'Cannoli';
               $food[85]['imgURL'] = 'FriedCheese.jpg';
               $food[85]['price'] = '5.99';
$food[86] = array()

               $food[86]['category'] = 'Desserts';
               $food[86]['name'] = 'Tiramisu';
               $food[86]['imgURL'] = 'garlicBread.jpg';
               $food[86]['price'] = '5.99';
$food[87] = array()
               $food[87]['category'] = 'Drinks';
               $food[87]['name'] = 'Beverages';
               $food[87]['description'] = 'Coke, Diet Coke, Sprite, Dr.Pepper, Lemonade, Fanta, Iced Tea, Domestic Coffee';
               $food[87]['imgURL'] = 'FriedCheese.jpg';
               $food[87]['price'] = '2.79';
 $food[88] = array()
               $food[88]['category'] = 'Full Bar';
               $food[88]['name'] = 'Full Bar';
               $food[88]['description'] = 'Wine, Domestic Beer, Imported Beer, & Mixed Drinks';
               $food[88]['imgURL'] = 'FriedCheese.jpg';
?>
