<?php
$item = '<img class="itemPic"src="images/menuExample.jpg">
<h4 class="menu_title">Garlic Bread</h4>
<p class="cost">$2.99</p>';

setcookie("itemSelect", $item, time() + 14400);
// Cookies will only be available beginning next page load.  (So $_COOKIE['user'], which we just set up in the line above, is not avaible "now".) To use this cookie item "now" (this page load), we need to also assign the same value to the same $_COOKIE array item as below.
$_COOKIE['itemSelect'] = $item;

$food = array();

$food[0] = array()

               $food[0]['category'] = 'Appetizer';
               $food[0]['name'] = 'Garlic Bread';
               $food[0]['imgURL'] = 'garlicBread.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[0]['price'] = '2.99';
$food[1] = array()
               $food[1]['category'] = 'Appetizer';
               $food[1]['name'] = 'Garlic Bread w/ Cheese';
               $food[1]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[1]['price'] = '4.50';

$food[2] = array()
        $food[2]['category'] = 'Appetizer';
        $food[2]['name'] = 'Fried Cheese';
        $food[2]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
        $food[2]['price'] = '6.99';

$food[3] = array()
                $food[3]['category'] = 'Appetizer';
                $food[3]['name'] = 'Fried Calamari';
                $food[3]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[3]['price'] = '9.99';

$food[4] = array()
                $food[4]['category'] = 'Salads';
                $food[4]['name'] = 'Tossed Salad';
                $food[4]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[4]['price'] = '3.50';

$food[5] = array()
                $food[5]['category'] = 'Salads';
                $food[5]['name'] = 'Bella Salad';
                $food[5]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[5]['price'] = '5.99';

$food[6] = array()
                $food[6]['category'] = 'Salads';
                $food[6]['name'] = 'Ceaser Salad';
                $food[6]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[6]['price'] = '7.99';
$food[7] = array()
                $food[7]['category'] = 'Salads';
                $food[7]['name'] = 'Antipasto Salad';
                $food[7]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[7]['price'] = '9.99';
$food[8] = array()
                $food[8]['category'] = 'Side Orders';
                $food[8]['name'] = 'Meat Sauce';
                $food[8]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[8]['price'] = '4.00';
$food[9] = array()
                $food[9]['category'] = 'Side Orders';
                $food[9]['name'] = 'Meatballs';
                $food[9]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[9]['price'] = '4.00';
$food[10] = array()
                $food[10]['category'] = 'Side Orders';
                $food[10]['name'] = 'Italian Sausage';
                $food[10]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[10]['price'] = '4.00';

$food[11] = array()
                $food[11]['category'] = 'Side Orders';
                $food[11]['name'] = 'French Fries';
                $food[11]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[11]['price'] = '4.00';
$food[12] = array()
                $food[12]['category'] = 'Side Orders';
                $food[12]['name'] = 'Alfredo Sauce';
                $food[12]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[12]['price'] = '5.00';
$food[13] = array()
                $food[13]['category'] = 'Side Orders';
                $food[13]['name'] = 'Fri Diavlo Sauce';
                $food[13]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[13]['price'] = '5.00';
$food[14] = array()
                $food[14]['category'] = 'Side Orders';
                $food[14]['name'] = 'Side of Mixed Vegetables';
                $food[14]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[14]['price'] = '5.99';
$food[15] = array()
                $food[15]['category'] = 'Side Orders';
                $food[15]['name'] = 'Side Dressings';
                $food[15]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[15]['price'] = '1.00';
$food[16] = array()
                $food[16]['category'] = 'Side Orders';
                $food[16]['name'] = 'Mozzarella';
                $food[16]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[16]['price'] = '1.50';
$food[17] = array()
                $food[17]['category'] = 'Side Orders';
                $food[17]['name'] = 'Homemade Rolls';
                $food[17]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[17]['price'] = '2.50';
$food[18] = array()
                $food[18]['category'] = 'Child Menu';
                $food[18]['name'] = 'Spaghetti and Meatballs';
                $food[18]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[18]['price'] = '5.99';
$food[19] = array()
                $food[19]['category'] = 'Child Menu';
                $food[19]['name'] = 'Baked Ziti';
                $food[19]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[19]['price'] = '5.99';
$food[20] = array()
                $food[20]['category'] = 'Child Menu';
                $food[20]['name'] = 'Chicken Strips';
                $food[20]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[20]['price'] = '5.99';
$food[21] = array()
                $food[21]['category'] = 'Child Menu';
                $food[21]['name'] = 'Small Pizza (Dine in Only)';
                $food[21]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[21]['price'] = '7.99';
$food[22] = array()
                $food[22]['category'] = 'Sandwiches';
                $food[22]['name'] = 'Ham and Cheese';
                $food[22]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[22]['price'] = '8.99';
$food[23] = array()
                $food[23]['category'] = 'Sandwiches';
                $food[23]['name'] = 'Super Sub';
                $food[23]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[23]['price'] = '8.99';
$food[24] = array()
                $food[24]['category'] = 'Hot Subs';
                $food[24]['name'] = 'Meatball Parmigiana';
                $food[24]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[24]['price'] = '8.99';
$food[25] = array()
                $food[25]['category'] = 'Hot Subs';
                $food[25]['name'] = 'Sausage Parmigiani';
                $food[25]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[25]['price'] = '8.99';
$food[26] = array()
                $food[26]['category'] = 'Hot Subs';
                $food[26]['name'] = 'Chicken Parmigiani';
                $food[26]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[26]['price'] = '8.99';
$food[27] = array()
                $food[27]['category'] = 'Hot Subs';
                $food[27]['name'] = 'Philly Cheese Steak';
                $food[27]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[27]['price'] = '8.99';

$food[28] = array()

                $food[28]['category'] = 'Pasta Plus';
                $food[28]['name'] = 'Marinara Sauce';
                $food[28]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[28]['price'] = '8.50';
$food[29] = array()
                $food[29]['category'] = 'Pasta Plus';
                $food[29]['name'] = 'Meat Sauce';
               $food[29]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[29]['price'] = '9.50';
$food[30] = array()
                $food[30]['category'] = 'Pasta Plus';
                $food[30]['name'] = 'Meatballs or Sausage';
                $food[30]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[30]['price'] = '9.50';
$food[31] = array()

                $food[31]['category'] = 'Pasta Plus';
                $food[31]['name'] = 'Mushrooms or Black Olives';
                $food[31]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[31]['price'] = '9.50';
$food[32] = array()
                $food[32]['category'] = 'Baked Pasta';
                $food[32]['name'] = 'Lasagna';
                $food[32]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[32]['price'] = '9.50';
 $food[33] = array()
                $food[33]['category'] = 'Baked Pasta';
                $food[33]['name'] = 'Cannelloni';
                $food[33]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[33]['price'] = '9.50';
$food[34] = array()
                $food[34]['category'] = 'Baked Pasta';
                $food[34]['name'] = 'Manicotti';
                $food[34]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[34]['price'] = '9.50';
$food[35] = array()
                $food[35]['category'] = 'Baked Pasta';
                $food[35]['name'] = 'Stuffed Shells';
                $food[35]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[35]['price'] = '9.50';
$food[36] = array()
                $food[36]['category'] = 'Baked Pasta';
                $food[36]['name'] = 'Cheese Ravioli';
                $food[36]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[36]['price'] = '9.50';
$food[37] = array()
                $food[37]['category'] = 'Baked Pasta';
                $food[37]['name'] = 'Baked Ziti';
                $food[37]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[37]['price'] = '9.50';
$food[38] = array()
                $food[38]['category'] = 'Baked Pasta';
                $food[38]['name'] = 'Baked Torellini';
                $food[38]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[38]['price'] = '9.50';
$food[39] = array()
                $food[39]['category'] = 'Baked Pasta';
                $food[39]['name'] = 'Eggplant Parmigiana';
                $food[39]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[39]['price'] = '9.50';
$food[40] = array()
                $food[40]['category'] = 'Baked Pasta';
                $food[40]['name'] = 'Eggplant Rollatini';
                $food[40]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[40]['price'] = '9.50';
$food[41] = array()
                $food[41]['category'] = 'Baked Pasta';
                $food[41]['name'] = 'Pasta Combo';
                $food[41]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[41]['price'] = '9.50';
$food[42] = array()
                $food[42]['category'] = 'Pasta Favorites';
                $food[42]['name'] = 'Fettuccine Molto Mio';
                $food[42]['description'] = 'Sun-dried tomatoes, onions, artichoke hearts & mushrooms in a creamy pink sauce';
                $food[42]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[42]['price'] = '10.50';
$food[43] = array()
                $food[43]['category'] = 'Pasta Favorites';
                $food[43]['name'] = 'Fettuccine Alfredo';
                $food[43]['description'] = 'Sauteed in a creamy cheese sauce';
                $food[43]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[43]['price'] = '10.50';
$food[44] = array()
                $food[44]['category'] = 'Pasta Favorites';
                $food[44]['name'] = 'Fettuccine Leonardo';
                $food[44]['description'] = 'Bacon and red onions in a creamy sauce';
                $food[44]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[44]['price'] = '10.50';
$food[45] = array()
                $food[45]['category'] = 'Pasta Favorites';
                $food[45]['name'] = 'Ziti Vodka';
                $food[45]['description'] = 'Sauteed with prosciutto & red onions in a vodka-pink sauce';
                $food[45]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[45]['price'] = '10.50';
$food[46] = array()
                $food[46]['category'] = 'Pasta Favorites';
                $food[46]['name'] = 'Tortellini Michelangelo';
                $food[46]['description'] = 'Stuffed macaroni sauteed with onion, bacon, diced tomatoes & artichoke hearts in a pink sauce';
                $food[46]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[46]['price'] = '10.50';
$food[47] = array()
                $food[47]['category'] = 'Pasta Favorites';
                $food[47]['name'] = 'Tortellini Panne';
                $food[47]['description'] = 'Sauteed in a cream cheese sauce';
                $food[47]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[47]['price'] = '10.50';
$food[48] = array()
                $food[48]['category'] = 'Pasta Favorites';
                $food[48]['name'] = 'Beef Ravioli';
                $food[48]['description'] = '(with your choice of sauce)';
                $food[48]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[48]['price'] = '10.50';
$food[49] = array()
                $food[49]['category'] = 'Pasta Favorites';
                $food[49]['name'] = 'Spinach Ravioli';
                $food[49]['description'] = '(with your choice of sauce)';
                $food[49]['imgURL'] = 'menuExample.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[49]['price'] = '10.50';
$food[50] = array()
                $food[50]['category'] = 'Chicken Entrees';
                $food[50]['name'] = 'Chicken Luma de Mare';
                 $food[50]['description'] = 'Chicken Breast stuffed with shrimp, crabmeat, mushrooms, spinach, mozzarella cheese in your choice of marsala or pink sauce w/ mushrooms & onions';
                $food[50]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[50]['price'] = '15.99';
$food[51] = array()
                $food[51]['category'] = 'Chicken Entrees';
                $food[51]['name'] = 'Chicken Cordon Bleu';
                $food[51]['description'] = 'Chicken breast stuffed with sun-dried tomatoes, mushrooms, spinach, mozzarella cheese in a pink sauce with two shrimp';
                $food[51]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[51]['price'] = '15.99';

$food[52] = array()
                $food[52]['category'] = 'Chicken Entrees';
                $food[52]['name'] = 'Chicken Cordon Bleu';
                $food[52]['description'] = 'Chicken breast stuffed with sun-dried tomatoes, mushrooms, spinach, mozzarella cheese in a pink sauce with two shrimp';
                $food[52]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[52]['price'] = '15.99';
$food[53] = array()
                $food[53]['category'] = 'Chicken Entrees';
                $food[53]['name'] = 'Chicken Ala Mike';
                $food[53]['description'] = 'Mushrooms, artichoke hearts, sun-dried tomatoes, onions, & green peppers in a creamy pink sauce';
                $food[53]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[53]['price'] = '11.99';
$food[54] = array()
                $food[54]['category'] = 'Chicken Entrees';
                $food[54]['name'] = 'Chicken Bella Vita';
                $food[54]['description'] = 'Topped with eggplant and cheese in a pink sauce';
                $food[54]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[54]['price'] = '11.99';
$food[55] = array()
                $food[55]['category'] = 'Chicken Entrees';
                $food[55]['name'] = 'Chicken Crimora';
                $food[55]['description'] = 'Sauteed with mushrooms & red onions in a brandy cream sauce';
                $food[55]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[55]['price'] = '11.99';
$food[56] = array()
                $food[56]['category'] = 'Chicken Entrees';
                $food[56]['name'] = 'Chicken Veggie';
                $food[56]['description'] = 'Veggies in a white wine sauce';
                $food[56]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[56]['price'] = '11.99';
$food[57] = array()
                $food[57]['category'] = 'Chicken Entrees';
                $food[57]['name'] = 'Chicken Scarparella';
                $food[57]['description'] = 'Mushrooms, onion, peppers & Italian sausage in a marinara sauce';
                $food[57]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[57]['price'] = '11.99';
$food[58] = array()
                $food[58]['category'] = 'Chicken Entrees';
                $food[58]['name'] = 'Chicken Pizzaolo';
                $food[58]['description'] = 'Mushrooms, peppers, & onions in a marinara sauce';
                $food[58]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[58]['price'] = '11.99';
$food[59] = array()
                $food[59]['category'] = 'Chicken Entrees';
                $food[59]['name'] = 'Chicken Marsala';
                $food[59]['description'] = 'Sauteed mushrooms & parsley in a sweet marsala wine sauce';
                $food[59]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[59]['price'] = '11.99';

$food[60] = array()
                $food[60]['category'] = 'Chicken Entrees';
                $food[60]['name'] = 'Chicken Piccata';
                $food[60]['description'] = 'Sauteed lemon & butter in a white wine sauce with capers';
                $food[60]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[60]['price'] = '11.99';
$food[61] = array()
                $food[61]['category'] = 'Chicken Entrees';
                $food[61]['name'] = 'Chicken Scampi';
                $food[61]['description'] = 'Garlic & lemon in a white wine sauce';
                $food[61]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[61]['price'] = '11.99';
$food[62] = array()
                $food[62]['category'] = 'Chicken Entrees';
                $food[62]['name'] = 'Chicken Parmigiana';
                $food[62]['description'] = 'Topped with marinara sauce & melted cheese';
                $food[62]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[62]['price'] = '11.99';
$food[63] = array()
                $food[63]['category'] = 'Seafood Entrees';
                $food[63]['name'] = 'Seafood Combo';
                $food[63]['description'] = 'Shrimp, mussels, calamari & crab in a garli white wine and light marinara sauce';
                $food[63]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[63]['price'] = '16.99';
$food[64] = array()
                $food[64]['category'] = 'Seafood Entrees';
                $food[64]['name'] = 'Shrimp Scampi';
                $food[64]['description'] = 'Garlic and lemon in a white wine sauce';
                $food[64]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[64]['price'] = '14.99';
$food[65] = array()
                $food[65]['category'] = 'Seafood Entrees';
                $food[65]['name'] = 'Shrimp Fri Diavlo';
                $food[65]['description'] = 'Garlic and white wine i na hot & spicy or sweet marinara sauce';
                $food[65]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[65]['price'] = '14.50';
$food[66] = array()
                $food[66]['category'] = 'Seafood Entrees';
                $food[66]['name'] = 'Shrimp Arabiata';
                $food[66]['description'] = 'Onions, mushrooms, peppers & white win in a light marinara sauce';
                $food[66]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[66]['price'] = '14.50';
$food[67] = array()
                $food[67]['category'] = 'Seafood Entrees';
                $food[67]['name'] = 'Mussels Fri Diavlo';
                $food[67]['description'] = 'Sauteed mushrooms & parsley in a sweet marsala wine sauce';
                $food[67]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[67]['price'] = '14.50';
$food[68] = array()
                $food[68]['category'] = 'Seafood Entrees';
                $food[68]['name'] = 'Shrimp Alfredo';
                $food[68]['description'] = 'Sauteed lemon & butter in a white wine sauce with capers';
                $food[68]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[68]['price'] = '14.50';
$food[61] = array()
                $food[61]['category'] = 'Seafood Entrees';
                $food[61]['name'] = 'Linguini & Clams';
                $food[61]['description'] = 'Over a white or red clam sauce';
                $food[61]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[61]['price'] = '13.50';
$food[62] = array()
                $food[62]['category'] = 'Chicken Entrees';
                $food[62]['name'] = 'Lobster Ravioli';
                $food[62]['description'] = 'Four raviolis stuffed with lobster in a pink sauce';
                $food[62]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[62]['price'] = '13.50';
$food[70] = array()
              $food[70]['category'] = 'Neapolitan Style Pizza';
              $food[70]['name'] = 'Medium 14 inch pizza w/ cheese';
              $food[70]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[70]['price'] = '9.99';
$food[71] = array()
              $food[71]['category'] = 'Neapolitan Style Pizza';
              $food[71]['name'] = 'Large 16 inch pizza w/ cheese';
              $food[71]['imgURL'] = 'garlicBread.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[71]['price'] = '10.99';
$food[72] = array()
              $food[72]['category'] = 'Pizza Toppings';
              $food[72]['name'] = 'Pizza Toppings';
              $food[72]['description'] = 'Green Peppers, Beef Sausage, Canadian Bacon, Pepperoni, Cheese, Black Olives, Onions, Mushrooms, Anchovies, Jalapenos';
              $food[72]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[72]['price'] = '1.50';
$food[73] = array()
              $food[73]['category'] = 'Specialty Toppings';
              $food[73]['name'] = '$1 Toppings';
              $food[73]['description'] = 'Fresh Garlic or Fresh Basil';
              $food[73]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[73]['price'] = '1.00';
$food[74] = array()

              $food[74]['category'] = 'Specialty Toppings';
              $food[74]['name'] = '$2 Toppings';
              $food[74]['description'] = 'Fresh Tomoatoes, Spinach, Extra Pizza Sauce';
              $food[74]['imgURL'] = 'garlicBread.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[74]['price'] = '2.00';
$food[75] = array()
              $food[75]['category'] = 'Specialty Toppings';
              $food[75]['name'] = '$3 Toppings';
              $food[75]['description'] = 'Riccota Cheese';
              $food[75]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[75]['price'] = '3.00';
$food[76] = array()
              $food[76]['category'] = 'Specialty Toppings';
              $food[76]['name'] = '$4 Toppings';
              $food[76]['description'] = 'Grilled Chicken, Artichoke Hearts, Alfredo Sauce, Italian Sausage, Meatballs';
              $food[76]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
              $food[76]['price'] = '4.00';
$food[77] = array()

              $food[77]['category'] = 'Specialty Pizza';
              $food[77]['name'] = 'Special Medium Pizza';
              $food[77]['imgURL'] = 'garlicBread.jpg';
              $food[77]['price'] = '13.99';
$food[78] = array()
              $food[78]['category'] = 'Specialty Pizza';
              $food[78]['name'] = 'Special Large Pizza';
              $food[78]['imgURL'] = 'FriedCheese.jpg';
              $food[78]['price'] = '15.99';
$food[79] = array()
              $food[79]['category'] = 'Specialty Pizza';
              $food[79]['name'] = 'Sicilian Deep Dish - Cheese';
              $food[79]['imgURL'] = 'FriedCheese.jpg';
              $food[79]['price'] = '14.99';
$food[80] = array()

              $food[80]['category'] = 'Specialty Pizza';
              $food[80]['name'] = 'Special Deep Dish';
              $food[80]['imgURL'] = 'garlicBread.jpg';
              $food[80]['price'] = '19.99';
$food[81] = array()
              $food[81]['category'] = 'Specialty Pizza';
              $food[81]['name'] = 'Stromboli with All Pizza Ingredients';
              $food[81]['imgURL'] = 'FriedCheese.jpg';
              $food[81]['price'] = '8.50';
$food[82] = array()
              $food[82]['category'] = 'Specialty Pizza';
              $food[82]['name'] = 'Calzone w/ Sausage, Ricotta, & Mozzarella';
              $food[82]['imgURL'] = 'FriedCheese.jpg';
              $food[82]['price'] = '8.50';
$food[83] = array()

              $food[83]['category'] = 'Desserts';
              $food[83]['name'] = 'Plain Cheesecake';
              $food[83]['imgURL'] = 'garlicBread.jpg';
              $food[83]['price'] = '5.99';
$food[84] = array()
              $food[84]['category'] = 'Desserts';
              $food[84]['name'] = 'Chocolate Cheesecake';
              $food[84]['imgURL'] = 'FriedCheese.jpg';
              $food[84]['price'] = '5.99';
$food[85] = array()
              $food[85]['category'] = 'Desserts';
              $food[85]['name'] = 'Cannoli';
              $food[85]['imgURL'] = 'FriedCheese.jpg';
              $food[85]['price'] = '5.99';
$food[86] = array()

              $food[86]['category'] = 'Desserts';
              $food[86]['name'] = 'Tiramisu';
              $food[86]['imgURL'] = 'garlicBread.jpg';
              $food[86]['price'] = '5.99';
$food[87] = array()
              $food[87]['category'] = 'Drinks';
              $food[87]['name'] = 'Beverages';
              $food[87]['description'] = 'Coke, Diet Coke, Sprite, Dr.Pepper, Lemonade, Fanta, Iced Tea, Domestic Coffee';
              $food[87]['imgURL'] = 'FriedCheese.jpg';
              $food[87]['price'] = '2.79';
$food[88] = array()
              $food[88]['category'] = 'Full Bar';
              $food[88]['name'] = 'Full Bar';
              $food[88]['description'] = 'Wine, Domestic Beer, Imported Beer, & Mixed Drinks';
              $food[88]['imgURL'] = 'FriedCheese.jpg';
?>
