<?php
$item = '<img class="itemPic"src="images/menuExample.jpg">
<h4 class="menu_title">Garlic Bread</h4>
<p class="cost">$2.99</p>';

setcookie("itemSelect", $item, time() + 14400);
// Cookies will only be available beginning next page load.  (So $_COOKIE['user'], which we just set up in the line above, is not avaible "now".) To use this cookie item "now" (this page load), we need to also assign the same value to the same $_COOKIE array item as below.
$_COOKIE['itemSelect'] = $item;

$food = array();

$food[0] = array()

               $food[0]['category'] = 'Appetizer';
               $food[0]['name'] = 'Garlic Bread';
               $food[0]['imgURL'] = 'garlicBread.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[0]['price'] = '2.99';
$food[1] = array()
               $food[1]['category'] = 'Appetizer';
               $food[1]['name'] = 'Garlic Bread w/ Cheese';
               $food[1]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
               $food[1]['price'] = '4.50';

$food[2] = array()
        $food[2]['category'] = 'Appetizer';
        $food[2]['name'] = 'Fried Cheese';
        $food[2]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
        $food[2]['price'] = '6.99';

$food[3] = array()
                $food[3]['category'] = 'Appetizer';
                $food[3]['name'] = 'Fried Calamari';
                $food[3]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[3]['price'] = '9.99';

$food[4] = array()
                $food[4]['category'] = 'Salads';
                $food[4]['name'] = 'Tossed Salad';
                $food[4]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[4]['price'] = '3.50';

$food[5] = array()
                $food[5]['category'] = 'Salads';
                $food[5]['name'] = 'Bella Salad';
                $food[5]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[5]['price'] = '5.99';

$food[6] = array()
                $food[6]['category'] = 'Salads';
                $food[6]['name'] = 'Ceaser Salad';
                $food[6]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[6]['price'] = '7.99';
$food[7] = array()
                $food[7]['category'] = 'Salads';
                $food[7]['name'] = 'Antipasto Salad';
                $food[7]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[7]['price'] = '9.99';
$food[8] = array()
                $food[8]['category'] = 'Side Orders';
                $food[8]['name'] = 'Meat Sauce';
                $food[8]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[8]['price'] = '4.00';
$food[9] = array()
                $food[9]['category'] = 'Side Orders';
                $food[9]['name'] = 'Meatballs';
                $food[9]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[9]['price'] = '4.00';
$food[10] = array()
                $food[10]['category'] = 'Side Orders';
                $food[10]['name'] = 'Italian Sausage';
                $food[10]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[10]['price'] = '4.00';

$food[11] = array()
                $food[11]['category'] = 'Side Orders';
                $food[11]['name'] = 'French Fries';
                $food[11]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[11]['price'] = '4.00';
$food[12] = array()
                $food[12]['category'] = 'Side Orders';
                $food[12]['name'] = 'Alfredo Sauce';
                $food[12]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[12]['price'] = '5.00';
$food[13] = array()
                $food[13]['category'] = 'Side Orders';
                $food[13]['name'] = 'Fri Diavlo Sauce';
                $food[13]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[13]['price'] = '5.00';
$food[14] = array()
                $food[14]['category'] = 'Side Orders';
                $food[14]['name'] = 'Side of Mixed Vegetables';
                $food[14]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[14]['price'] = '5.99';
$food[15] = array()
                $food[15]['category'] = 'Side Orders';
                $food[15]['name'] = 'Side Dressings';
                $food[15]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[15]['price'] = '1.00';
$food[16] = array()
                $food[16]['category'] = 'Side Orders';
                $food[16]['name'] = 'Mozzarella';
                $food[16]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[16]['price'] = '1.50';
$food[17] = array()
                $food[17]['category'] = 'Side Orders';
                $food[17]['name'] = 'Homemade Rolls';
                $food[17]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[17]['price'] = '2.50';
$food[18] = array()
                $food[18]['category'] = 'Child Menu';
                $food[18]['name'] = 'Spaghetti and Meatballs';
                $food[18]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[18]['price'] = '5.99';
$food[19] = array()
                $food[19]['category'] = 'Child Menu';
                $food[19]['name'] = 'Baked Ziti';
                $food[19]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[19]['price'] = '5.99';
$food[20] = array()
                $food[20]['category'] = 'Child Menu';
                $food[20]['name'] = 'Chicken Strips';
                $food[20]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[20]['price'] = '5.99';
$food[21] = array()
                $food[21]['category'] = 'Child Menu';
                $food[21]['name'] = 'Small Pizza (Dine in Only)';
                $food[21]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[21]['price'] = '7.99';
$food[22] = array()
                $food[22]['category'] = 'Sandwiches';
                $food[22]['name'] = 'Ham and Cheese';
                $food[22]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[22]['price'] = '8.99';
$food[23] = array()
                $food[23]['category'] = 'Sandwiches';
                $food[23]['name'] = 'Super Sub';
                $food[23]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[23]['price'] = '8.99';
$food[24] = array()
                $food[24]['category'] = 'Hot Subs';
                $food[24]['name'] = 'Meatball Parmigiana';
                $food[24]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[24]['price'] = '8.99';
$food[25] = array()
                $food[25]['category'] = 'Hot Subs';
                $food[25]['name'] = 'Sausage Parmigiani';
                $food[25]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[25]['price'] = '8.99';
$food[26] = array()
                $food[26]['category'] = 'Hot Subs';
                $food[26]['name'] = 'Chicken Parmigiani';
                $food[26]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[26]['price'] = '8.99';
$food[27] = array()
                $food[27]['category'] = 'Hot Subs';
                $food[27]['name'] = 'Philly Cheese Steak';
                $food[27]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[27]['price'] = '8.99';
$food[50] = array()
                $food[50]['category'] = 'Chicken Entrees';
                $food[50]['name'] = 'Chicken Luma de Mare';
                 $food[50]['description'] = 'Chicken Breast stuffed with shrimp, crabmeat, mushrooms, spinach, mozzarella cheese in your choice of marsala or pink sauce w/ mushrooms & onions';
                $food[50]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[50]['price'] = '15.99';
$food[51] = array()
                $food[51]['category'] = 'Chicken Entrees';
                $food[51]['name'] = 'Chicken Cordon Bleu';
                $food[51]['description'] = 'Chicken breast stuffed with sun-dried tomatoes, mushrooms, spinach, mozzarella cheese in a pink sauce with two shrimp';
                $food[51]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[51]['price'] = '15.99';

$food[52] = array()
                $food[52]['category'] = 'Chicken Entrees';
                $food[52]['name'] = 'Chicken Cordon Bleu';
                $food[52]['description'] = 'Chicken breast stuffed with sun-dried tomatoes, mushrooms, spinach, mozzarella cheese in a pink sauce with two shrimp';
                $food[52]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[52]['price'] = '15.99';
$food[53] = array()
                $food[53]['category'] = 'Chicken Entrees';
                $food[53]['name'] = 'Chicken Ala Mike';
                $food[53]['description'] = 'Mushrooms, artichoke hearts, sun-dried tomatoes, onions, & green peppers in a creamy pink sauce';
                $food[53]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[53]['price'] = '11.99';
$food[54] = array()
                $food[54]['category'] = 'Chicken Entrees';
                $food[54]['name'] = 'Chicken Bella Vita';
                $food[54]['description'] = 'Topped with eggplant and cheese in a pink sauce';
                $food[54]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[54]['price'] = '11.99';
$food[55] = array()
                $food[55]['category'] = 'Chicken Entrees';
                $food[55]['name'] = 'Chicken Crimora';
                $food[55]['description'] = 'Sauteed with mushrooms & red onions in a brandy cream sauce';
                $food[55]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[55]['price'] = '11.99';
$food[56] = array()
                $food[56]['category'] = 'Chicken Entrees';
                $food[56]['name'] = 'Chicken Veggie';
                $food[56]['description'] = 'Veggies in a white wine sauce';
                $food[56]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[56]['price'] = '11.99';
$food[57] = array()
                $food[57]['category'] = 'Chicken Entrees';
                $food[57]['name'] = 'Chicken Scarparella';
                $food[57]['description'] = 'Mushrooms, onion, peppers & Italian sausage in a marinara sauce';
                $food[57]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[57]['price'] = '11.99';
$food[58] = array()
                $food[58]['category'] = 'Chicken Entrees';
                $food[58]['name'] = 'Chicken Pizzaolo';
                $food[58]['description'] = 'Mushrooms, peppers, & onions in a marinara sauce';
                $food[58]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[58]['price'] = '11.99';
$food[59] = array()
                $food[59]['category'] = 'Chicken Entrees';
                $food[59]['name'] = 'Chicken Marsala';
                $food[59]['description'] = 'Sauteed mushrooms & parsley in a sweet marsala wine sauce';
                $food[59]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[59]['price'] = '11.99';

$food[60] = array()
                $food[60]['category'] = 'Chicken Entrees';
                $food[60]['name'] = 'Chicken Piccata';
                $food[60]['description'] = 'Sauteed lemon & butter in a white wine sauce with capers';
                $food[60]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[60]['price'] = '11.99';
$food[61] = array()
                $food[61]['category'] = 'Chicken Entrees';
                $food[61]['name'] = 'Chicken Scampi';
                $food[61]['description'] = 'Garlic & lemon in a white wine sauce';
                $food[61]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[61]['price'] = '11.99';
$food[62] = array()
                $food[62]['category'] = 'Chicken Entrees';
                $food[62]['name'] = 'Chicken Parmigiana';
                $food[62]['description'] = 'Topped with marinara sauce & melted cheese';
                $food[62]['imgURL'] = 'FriedCheese.jpg';  // if all your images are in the same folder, you only need the file name here
                $food[62]['price'] = '11.99';

?>
